### ISSUE TITLE
use full URI in HTTP Header or add to IANA link relations registry

### ISSUE THREAD

**Issue by elf-pavlik** [w3c/Micropub#1]
https://indiewebcamp.com/Micropub#HTTP_Header

[IANA link relations registry](http://www.iana.org/assignments/link-relations/link-relations.xhtml) does NOT include _micropub_ and following RFC5988 this rel should use full URI

> Note that extension relation types are REQUIRED to be absolute URIs
>    in Link headers, and MUST be quoted if they contain a semicolon (";")
>    or comma (",") (as these characters are used as delimiters in the
>    header itself).

https://tools.ietf.org/html/rfc5988#section-5.3

similar issue for Webmention https://github.com/converspace/webmention/issues/38

**Comment by jonnybarnes** [comment]
Do you mean the rel-value in the header? What could the full URI be?

**Comment by aaronpk** [comment]
The HTML5 link relations registry is http://microformats.org/wiki/existing-rel-values per both the [WHATWG HTML specification](https://html.spec.whatwg.org/multipage/semantics.html#other-link-types) and the [W3C HTML5 specification](http://www.w3.org/TR/html5/links.html#other-link-types). Any other registries are obsolete at this point, and any specs that reference the IETF or IANA registries should be updated to reference the Microformats registry.[[1]](http://indiewebcamp.com/irc/2015-04-13/line/1428941905168). 

Since the HTML rel value is `micropub`, and is going through the proper WHATWG and W3C registration process, I see no reason to use a separate rel value for the HTTP header even if the IETF spec wants to use its own registry of rel values. The same applies to Webmention, so I will just point to this issue from there.

**Comment by akuckartz** [comment]
Alternatively one can argue that both the WHATWG HTML specification and the W3C HTML5 specification are violating an IETF specification - and therefore should be corrected...

**Comment by gobengo** [comment]
IMO no one should be leaning on registries. Just use a URI. It's not that hard. At the very least use a urn like `urn:microformats.org:rels:micropub` or something.

URLs are even better for the future, though, as it provides an extension point (the locatable resource) down the line.

**Comment by tantek** [comment]
"One can argue" many things, but since no one is, certainly no one actually actively writing code that consumes rel values, such hypothetical weasel-wording (per WP) expressions of arguments can be summarily dismissed.
