### ISSUE TITLE
Consider using full "micropub-*" instead of "mp-*"

### ISSUE THREAD

**Issue by aaronpk** [w3c/Micropub#13]
"Spelled out is better documentation and less ambiguous." http://indiewebcamp.com/irc/2015-10-11/line/1444603018046

**Comment by veganstraightedge** [comment]
:+1:

**Comment by dissolve** [comment]
:+1: on this as well
while i feel like this follows the CSS method of vendor prefixes being short (-o-, -moz-, etc) there is really no need for the brevity here.

**Comment by voxpelli** [comment]
I'm not so sure on this one, I feel that it's easier to talk about `mp-syndicate-to`, `mp-action` and such on eg. IRC than to talk about `micropub-action`.

I'm also not so sure that there's actually anything to be spelled out here – the `mp-`-prefix is just a reserved namespace to avoid clashes with properties of micropub content – any prefix could be used really – a simple `-`, `_`, `$`, `⚡` could work just as well (disregarding whether that's actually a valid first character of a query parameter, I actually don't know that of the top of my head).

`mp-` is not a variable name or instruction that is directly related to micropub itself, if it were I think it would make more sense to fully spell it out. Eg. `mp-syndicate-to` is more of an instruction to a syndication service that extends micropub than it is a micropub instruction. Seen that way an abbreviated prefix could actually cause less confusion as it's more clear that it's a namespace and not something else. Partly because of previous familiarity with how such prefixes work from eg. vendor prefixes.

**Comment by veganstraightedge** [comment]
`webkit-` is spelled out.

**Comment by voxpelli** [comment]
My main point is that I think it's easier to talk about `mp-syndicate-to` than `micropub-syndicate-to` – while in theory I agree that spelling things out is a good thing to do in most cases, I feel that it in practice doesn't really apply in this case. Micropub should be evident by the context already.

All in all – I'd rather discuss `mp-*` properties on eg IRC than `micropub-*` ones.

**Comment by veganstraightedge** [comment]
I think optimizing for IRC discussion convenience is the wrong priority. 

(You can setup a text expansion from mp to micropub if you really don't wanna type it out.)

Users should come before implementers. And being unambiguous is better for users.

**Comment by dissolve** [comment]
Honestly I'm thinking it actually it's better to keep mp-  Users don't really see these,  they are really for implementors.  What sold me on it is the field micropub-syndicate-to. This becomes a confusion of syndicate via micropub, vs just syndicate.  Mp is clearly separate from the field name itself. 

On October 14, 2015 7:43:00 PM EDT, Shane Becker notifications@github.com wrote:

> I think optimizing for IRC discussion convenience is the wrong
> priority. 
> 
> (You can setup a text expansion from mp to micropub if you really don't
> wanna type it out.)
> 
> Users should come before implementers. And being unambiguous is better
> for users. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/aaronpk/Micropub/issues/13#issuecomment-148234166

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by karadaisy** [comment]
+1 for micropub-. If it's ambiguous for certain property names, then mp- can only be _more_ ambiguous imho

**Comment by karadaisy** [comment]
Although I will say, the other special properties (h and q) err on the side of being short. Should we consider spelling those out too? "micropub-post-type" or some such?

**Comment by voxpelli** [comment]
@veganstraightedge Do we have an actual case where `mp-` has been proven ambiguous?

**Comment by veganstraightedge** [comment]
All abbreviations are ambiguous. 

Just yesterday in the #indiewebcamp IRC channel, @tantek said "ACL" and multiple people didn't know what it meant.

**Comment by dissolve** [comment]
I'm now entirely :-1: on this, 
@veganstraightedge yes, all abbreviations can be ambiguous, but i don't think anyone would argue to never use abbreviations.   HTTP is an abbreviation, as is URL.  we don't go to hypertexttransferprotocolsecure://worldwideweb.indiewebcamp.com/ :stuck_out_tongue: 

It IS ambiguous when you use the expanded form though
micropub-post-type does not suggest any prefixing.

Actually I think the place where this would become the worst would be my attempts to use micropub to add new micropub syndication targets to my micropub endpoint.... 

So mpTweet was a micropub to twitter app I have been playing with.
Log in to twitter and your own site on the app, and mpTweet uses micropub to tell your endpoint add a new micropub syndication target, here is the url for it, here is the label, here is the key you will need, etc.  I realize this is an edge case though.

mp- is recognizable a prefix immediately since all other terms are expanded (except URL perhaps).  Seeing mp-post-type and its a pretty easy assumption that mp- is a prefix.  micropub-post-type and its not obvious.

mp- fits in with prefixing used by other systems a developer would already be using, like microformats, css, http headers, etc.

mp- prefixing also suggests that we could prefix in other ways for extensions
( btmb- or mp-btmb for fields that are custom to my site for example).  Maybe even doing so with the unstable with a -x-.

**Comment by aaronpk** [comment]
wow, I didn't expect to get such wildly differing opinions on this.

I do like the fact that with a short prefix, the name of the parameter stands out more:

 `mp-syndicate-to` vs `micropub-syndicate-to`

Frankly having it all spelled out makes it less clear what the goal of the parameter is, since it puts too much emphasis on the "micropub" aspect. I also think `micropub-url` is less clear than `mp-url` since it could mean the URL of the micropub endpoint.

I am leaning towards sticking with the `mp-*` prefix.

**Comment by karadaisy** [comment]
I don't have a strong objection to keeping `mp-` and do like that it is more consistent with the aesthetic of `h` and `q`

**Comment by tantek** [comment]
Really impressed with (and learning from) the thoughtful discussion here, much more than I expected! Everyone has pointed out insights that I think are worth documenting for the designs of names of such things, I'll see if I can capture them all somehow on the wiki. 

The points made here all also apply to prefix design for vendor specific microformats2 root and property class names. I'm not going to offer a specific opinion on mp-\* vs micropub-\* because I think everyone else's combined wisdom/discussion is clearly on track to resolve on a very well reasoned / thought through conclusion (whatever that is).

**Comment by veganstraightedge** [comment]
I documented the vendor prefixes that I know about or could find out about on the #indiewebcamp wiki.

https://indiewebcamp.com/Vendor-prefix

Most use short abbreviations. Most start with a leading hyphen.

**Comment by karadaisy** [comment]
So the prefix is an artifact of having to glom the control params and the data params into one flat list because of form encoding. Otherwise, we might model the request more naturally like

``` json
{
"action": "edit",
"url": "...",
"properties": { "content": "..." }
}
```

It occurs to me that PuSH denotes special properties like this with [the prefix `hub.`](http://pubsubhubbub.github.io/PubSubHubbub/pubsubhubbub-core-0.4.html#rfc.section.5.1)

I like `micropub.` or `mp.` as a better way to eliminate the ambiguity of whether `micropub-` is a prefix or not. (e.g. `micropub.syndication-url` or `mp.syndication-url`)

**Comment by aaronpk** [comment]
Yes, and in fact the JSON syntax looks a lot like that: http://indiewebcamp.com/micropub#Editing

Using "." is an interesting idea. The only problem is PHP converts it to "_" so you actually would have to reference `$_POST['micropub_syndicate-to']` in your code, despite all the docs saying `.`. I ran into this when trying to return the PuSH verification challenge.

**Comment by karadaisy** [comment]
bah, yeah that's not great. glad we have implementation experience to foresee stuff like that

**Comment by aaronpk** [comment]
I'm going to close this issue since there seem to be more reasons to use mp- than micropub-. That said, I am interested in finding an alternative that doesn't require prefixed names at all, or finding some other way to make this a non-issue entirely.
