### ISSUE TITLE
Uploading files that are referred to in the content

### ISSUE THREAD

**Issue by kevinmarks** [w3c/Micropub#35]
It's not clear in http://micropub.net/draft/#uploading-files if the url given in the multipart section for the uploaded photo can be referred to in the content posted at the same time.

Also, if the photo is sent by url reference, and the content links to it, does that imply the endpoint should rewrite the html content to refer to it's own copy?

**Comment by aaronpk** [comment]
You raise two issues here, but the second one is hopefully easy.

> It's not clear in http://micropub.net/draft/#uploading-files if the url given in the multipart section for the uploaded photo can be referred to in the content posted at the same time.

First, this would only apply when sending HTML content, since there isn't really a way to reference a relative URL in plaintext. Because when you upload a file you have to give it a property name (e.g. `photo` from `h-entry`), it doesn't really make sense to use that in the content of the post as well. I would say let's keep it simple and not allow this use case, since it's relatively complicated and works better using the Media Endpoint to first upload the photo. 

Maybe it's worth adding an example of using the Media Endpoint when writing a blog post that contains images? Currently Quill's HTML editor implements this flow, where when you add an image to the editor it actually uploads it to your Media Endpoint and then references that URL in an `<img>` tag in the HTML content.

---

> Also, if the photo is sent by url reference, and the content links to it, does that imply the endpoint should rewrite the html content to refer to it's own copy?

There is already a sentence in the spec that says:

> The endpoint may download a copy of the file at the URL and store it the same way it would store the file if it had been uploaded directly. [[3.3.1]](http://micropub.net/draft/#uploading-files)

Is this not clear? Basically it's up to the Micropub endpoint whether it wants to store its own copy of any files referenced by URL or just have the HTML hotlink the external image. I can see arguments for both options, and it doesn't need to be specified by the spec.

**Comment by kevinmarks** [comment]
It probably is worth explaining the endpoint process for a post with images in.

**Comment by aaronpk** [comment]
I just added a new example section, let me know if that looks okay to you!
