### ISSUE TITLE
no language or direction or localizability of error message?

### ISSUE THREAD

**Issue by r12a** [w3c/Micropub#36]
[comment by Addison Phillips]

https://www.w3.org/TR/micropub/#error-response

An error message is provided for here, but no language/direction metadata nor means of localizing it.

**Comment by aaronpk** [comment]
These error messages were modeled after the [OAuth 2.0 error](https://tools.ietf.org/html/rfc6749#section-5.2) format which says the messages are "used to assist the client developer in understanding the error that occurred". (In OAuth 2.0 the text is limited to ASCII.) Would you recommend adding a similar clarification of the intended use of the error description?

**Comment by aaronpk** [comment]
We talked about this in the last call and resolved to include a sentence similar to the OAuth 2.0 error response indicating that the error message is intended to assist the client developer and is not user visible. https://www.w3.org/wiki/Socialwg/2016-07-26-minutes#resolution-error-messsage

This is visible at https://www.w3.org/TR/micropub/#error-response

> The response body may also contain an error_description property with a human-readable description of the error message, used to assist the client developer in understanding the error. This is not meant to be shown to the end user.

**Comment by aphillips** [comment]
On 2016-11-10 the I18N WG [tasked me](https://www.w3.org/International/track/actions/569) with responding to this issue.

We are satisfied with this change as a resolution to our issue and will not re-open this item.

That said, the I18N WG does want to take a moment to frown heavily at OAuth 2.0 error_description as a model for error messages on the Web (or anywhere else). We understand the motivations behind the design in RFC6749, but modern, UTF-8-encoded messages that can be localized are more generally useful. `</rant>`

**Comment by akuckartz** [comment]
@aphillips Thanks for the "rant". I agree with it.

**Comment by aaronpk** [comment]
@aphillips I should clarify, I did not intend to limit the Micropub error messages to ASCII only. You'll note I didn't include "ASCII" in the text at all: https://www.w3.org/TR/micropub/#error-response

My intent was to allow the full UTF-8 character set since the response is in JSON which already supports UTF-8. The main concern I had was avoiding the need for a separate language marker, and certainly did not want to allow HTML in the description. By limiting the use of this text to client developers, we were hoping that would reduce the need for a more complete localization ability.
