### ISSUE TITLE
comparing mp-* actions to AS2.0 equivalents 

### ISSUE THREAD

**Issue by elf-pavlik** [w3c/Micropub#4]
### Background
- http://indiewebcamp.com/micropub#Syntax
- http://www.w3.org/TR/activitystreams-vocabulary/#activity-types

While currently AS2.0 mixes Human activities with API operations (https://github.com/w3c-social/social-vocab/issues/12) we can still compare syntax proposed by Micropub to one proposed by AS2.0 @jasnell
### Examples

```
mp-url=http://example.com/post/1
mp-action=delete
```

``` json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Delete",
  "@id": "http://example.com/api-calls/4b4d85bd-962e-47d0-9a53-4483e9818a78",
  "object": "http://example.com/post/1"
}
```

```
 mp-url=http://example.com/post/1
 mp-action=undelete
```

``` json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Undo",
  "object": "http://example.com/api-calls/4b4d85bd-962e-47d0-9a53-4483e9818a78"
}
```

or we could define custom Undelete and don't assign `@id` to delete operation

``` json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Delete",
  "object": "http://example.com/post/1"
}
```

``` json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Undelete",
  "object": "http://example.com/post/1"
}
```

we could also use media-type or profile to imply @context

``` json
{
  "object": "http://example.com/post/1",
  "type": "Delete"
}
```

which looks almost identical to 

```
mp-url=http://example.com/post/1
mp-action=delete
```

**Comment by aaronpk** [comment]
Interesting, but I'm not entirely clear what the question/suggestion is?

**Comment by elf-pavlik** [comment]
If AS2.0 becomes TR to _reuse_ it instead of trying to specify second not compatible approach. If needed and one can have automated conversion from AS2.0 verbs to micropub verbs, then we should specify it clearly. IMO we can't deliver in Social WG two misaligned specs!

**Comment by aaronpk** [comment]
In Activity Streams, the "Delete" activity is used to indicate an activity was deleted. In ActivityPub, a DELETE HTTP verb is used to actually perform the deletion. Since Activity Streams is meant to be a description of things that have happened, rather than actions to take, it doesn't make sense to try to re-use the vocabulary of it for the delete action of Micropub. This would be a better suggestion for publishing a Microformats feed of actions that were taken on a Micropub endpoint, for example listing all the delete actions that have happened.
