### ISSUE TITLE
Servers should send "501 Not Implemented" status for unimplemented #querying commands

### ISSUE THREAD

**Issue by cweiske** [w3c/Micropub#43]
Since the querying commands config, source and syndicate-to do not have to be implemented, servers SHOULD send a "HTTP/1.1 501 Not Implemented" status code when the client sends a `q` parameter value that the server does not support.

It is helpful for clients to know that they did not do wrong:
- When they get a 501, they can store that information and simply not ask the next time.
- If they get a 4xx status code, they could send an error notification to the developer or directly open a bug since they obviously did wrong.

---

Related to #41.

**Comment by dshanske** [comment]
I am in favor of this. Clients should check for it as well as an error.

**Comment by aaronpk** [comment]
What is the benefit to the client if it sees a `501` response from the server?

**Comment by dshanske** [comment]
It doesn't assume incorrect implementation on its part

**Comment by aaronpk** [comment]
Is there some user-visible thing the Micropub client can do that differs when the endpoint would return `501` vs returning either an empty response with `200` or an error response with `400`?

**Comment by dshanske** [comment]
Advise the user the server doesn't support it. That may prompt the user to advise the individual responsible for the server that they want this feature.

**Comment by voxpelli** [comment]
In practice the difference between a `501` and a `400` is very small and shouldn't really matter –  it only makes it clearer for the client that the "error" encountered is due to the server not implementing the feature rather than the client doing something wrong with it's request, so almost purely a Developer Experience thing, but possibly also a User Experience thing if the client wants to point out that the server is lacking support for the feature.

Any User Experience would probably also need the suggestion of a specific payload though, that describes the status in more detailed, as a `501` can be triggered for more reasons than the Micropub-specific ones.

Reading the actual specs another possible difference is that a `501` response apparently i cacheable by default while a `400` isn't, but not sure whether that actually is of any importance here.

Related docs:

`400`: https://tools.ietf.org/html/rfc7231#section-6.5.1
`501`: https://tools.ietf.org/html/rfc7231#section-6.6.2

**Comment by aaronpk** [comment]
From what I've been reading, it looks like `HTTP 501` is actually about whether the server supports the HTTP method rather than the contents of the request, so I don't think that's an appropriate response here. I propose closing this issue with no change to the spec.

**Comment by cweiske** [comment]
In my eyes "Unimplemented" covers standard things that this particular party does not implement - be it a HTTP request method, or, like here, a standard URL to query the micropub endpoint configuration.

Many web applications use the `X-Forwarded-For` HTTP header to send the client's IP to the API they are querying. This header was originally meant to be used by proxy servers only, but was thematically close enough to be used for the mentioned use case.
The same applies here with 501.

**Comment by akuckartz** [comment]
> In my eyes "Unimplemented" covers standard things that this particular party does not implement ...

The http specification (https://tools.ietf.org/html/rfc7231#section-6.6.2) does not seem to support this view.

**Comment by aaronpk** [comment]
@cweiske can you point to any examples of servers that return HTTP 501 for "unimplemented" things?

**Comment by cweiske** [comment]
- commentpara.de does; https://github.com/cweiske/anoweco/blob/master/www/micropub.php#L153
- many results on github for php code that sends out those servers: https://github.com/search?l=php&q=%22501+not+implemented%22&ref=searchresults&type=Code&utf8=%E2%9C%93
  - even go code does it: https://github.com/search?l=go&q=%22501+not+implemented%22&ref=searchresults&type=Code&utf8=%E2%9C%93
- known does it by default: https://github.com/idno/Known/blob/43373fea7e1e785dc878d984c38bb5319c274799/Idno/Common/Page.php#L198

**Comment by aaronpk** [comment]
How about a server that someone else wrote? Not necessarily Micropub either.

**Comment by aaronpk** [comment]
I was asking specifically about returning 501 for unimplemented functionality, rather than unimplemented HTTP methods. Links to any documentation or specs would be appreciated rather than a search for source code results.

**Comment by cweiske** [comment]
I won't follow up to this issue, so I'm closing it now.
