### ISSUE TITLE
File upload: Rename "photo" to "image"

### ISSUE THREAD

**Issue by cweiske** [w3c/Micropub#48]
Currently three file types are specified: `photo`, `audio` and `video`.

Both `audio` and `video` are identical to official MIME type media types, while `photo` is unprecedented.
To stay in line with MIME type media types, rename `photo` to `image`.

This would allow easier mapping of mime types to micropub file types since one can simply use the mime type's media type (the string before the slash).

**Comment by aaronpk** [comment]
As much as I agree that "image" is more consistent, the property names used in the examples are from the [h-entry](http://microformats.org/wiki/h-entry#Properties) vocabulary. In order for Micropub to recommend `image`, the h-entry spec would have to change to use that property as well. This is not something I want to block the Micropub spec on, so I propose closing this with no change.

**Comment by tantek** [comment]
As a summary update from the h-entry issue https://github.com/microformats/h-entry/issues/1 - there's good reasons and precedent for "photo" in h-entry.

As far as the mapping into Micropub, one way to consider this issue is how would someone upload a "u-featured" image or photo for an h-entry? Does that map as a new file type "featured"? Or does it re-use the "photo" file type?
