### ISSUE TITLE
comparing Patch to existing specifications

### ISSUE THREAD

**Issue by elf-pavlik** [w3c/Micropub#5]
http://indiewebcamp.com/micropub#Update

Seems to propose custom way of patching data. How does it compare to already existing specs?
- JSON Patch http://tools.ietf.org/html/rfc6902 ( http://jsonpatch.com/ )
- Linked Data Patch http://www.w3.org/TR/ldpatch/ (CR)

**Comment by aaronpk** [comment]
jsonpatch looks interesting, I wonder how that could be translated to a form-encoded request. The nice thing about the way micropub currently describes updates is that it maps relatively cleanly to form encoding. Also so far no micropub vocabularies have nested elements, so the "path" for micropub updates would always be one level deep.

**Comment by aaronpk** [comment]
I just read through the JSON Patch spec, and it looks like it might actually be too strict to be useful here.

Here's an example of adding a syndication URL: http://indiewebcamp.com/micropub-edit-examples#JSON_Patch Note the problem described on the wiki.

Additionally, we would not use the HTTP PATCH verb, and would instead wrap the Patch document so that it can be sent in a regular POST request.

**Comment by aaronpk** [comment]
Closing this based on previous comments.
