### ISSUE TITLE
Allow a 202 Accepted from Media Endpoint uploads

### ISSUE THREAD

**Issue by barryf** [w3c/Micropub#64]
For my Media Endpoint I'm uploading files to GitHub and serving them back with GitHub Pages. Unfortunately there's a lag between a completed upload and being able to serve the file.

In the Micropub spec, [section 3.6.4](https://micropub.net/draft/#response-3) requires a `201 Created` but it's possible that the file isn't immediately available. Test 700 in Micropub.rocks fails for me as a result.

I could add an arbitrary "wait" in my code but I wondered with a `202 Accepted` would be acceptable (excuse the pun)?

**Comment by aaronpk** [comment]
Unfortunately, the flow outlined in the [media endpoint diagram](https://www.w3.org/TR/micropub/#media-endpoint) won't work with a 202 response. The client needs to know the resulting URL in order to include it in a follow-up request to create a post.

Your server doesn't need to wait before the publish finishes as long as it knows what URL the file will be available at. It can return 201 before the file is technically available at the URL. The main point is that the client needs to know the URL of the uploaded file in the response.

**Comment by barryf** [comment]
Thanks @aaronpk. That makes sense. I've rewritten to use S3 for storage and I can now immediately respond with a `201` to pass the tests.
